"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const client_1 = require("../controllers/client");
const router = (0, express_1.Router)();
exports.router = router;
router.post("/", client_1.getClients);
router.get("/:id", client_1.getClientById);
router.post("/create", client_1.createClient);
router.put("/:id", client_1.updateClient);
