"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const product_1 = require("../controllers/product");
const router = (0, express_1.Router)();
exports.router = router;
router.post("/", product_1.getProducts);
router.get("/:id", product_1.getProduct);
router.post("/create", product_1.createProduct);
router.put("/:id", product_1.updateProduct);
router.delete("/:id", product_1.deleteProduct);
